### ISSUE TITLE
better UX when adding a photo in the wizard 

### ISSUE THREAD

**Issue by paarals** [openpoke/decidim-module-reporting-proposals#52]
When I click on the button, I already get an error. From UX perspective this is not very nice.

Steps to reproduce:
1. Click on add photo
2. don't add any photo
3. see error 
![image](https://user-images.githubusercontent.com/1401520/217842540-73b20243-3944-41b9-b04c-36ffcebbd08b.png)

related to #13

**Comment by microstudi** [comment]
closed by #57
